# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bU-zX6gRWlh6nxOgEPSn7O_Hjn3zp9he
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as sco
import google.generativeai as genai

st.set_page_config(page_title="AI 智能投資分析平台", layout="wide")

# ==========================================
# 1. Core Functions Setup
# ==========================================

def get_gemini_response(prompt):
    try:
        api_key = st.secrets.get("GEMINI_API_KEY", "")
        if not api_key:
            return None
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-2.5-flash")
        safe_prompt = f"""
        你是一位財務分析師。請根據使用者提供的 Python 計算結果進行分析。
        請注意：
        1. 不要提供買進、賣出、加碼、減碼、停損或停利建議。
        2. 不要提供目標價。
        3. 不要保證未來績效。
        4. 只能根據使用者提供的數據進行分析。
        5. 請明確提醒本分析不構成投資建議。
        使用者資料如下：
        {prompt}
        """
        response = model.generate_content(safe_prompt)
        return response.text
    except Exception as e:
        return f"Gemini API 呼叫失敗：{e}"

def flatten_columns(df):
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = ['_'.join(col).strip() for col in df.columns.values]
    return df

def download_stock_data(ticker, start_date, end_date):
    df = yf.download(ticker, start=start_date, end=end_date)
    if isinstance(df.columns, pd.MultiIndex):
        try:
            df = df['Close'].to_frame()
            df.columns = ['Close']
        except:
            df.columns = df.columns.get_level_values(0)
    return df

def calculate_indicators(df):
    if 'Close' not in df.columns:
        return df

    close = df['Close']
    df['SMA20'] = close.rolling(window=20).mean()
    df['SMA60'] = close.rolling(window=60).mean()

    delta = close.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    df['RSI14'] = 100 - (100 / (1 + rs))

    ema12 = close.ewm(span=12, adjust=False).mean()
    ema26 = close.ewm(span=26, adjust=False).mean()
    df['MACD'] = ema12 - ema26
    df['MACD_signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['MACD_diff'] = df['MACD'] - df['MACD_signal']

    df['BB_middle'] = df['SMA20']
    df['BB_std'] = close.rolling(window=20).std()
    df['BB_upper'] = df['BB_middle'] + 2 * df['BB_std']
    df['BB_lower'] = df['BB_middle'] - 2 * df['BB_std']

    df['Daily_Return'] = close.pct_change()
    df['Cum_Wealth'] = (1 + df['Daily_Return'].fillna(0)).cumprod()
    df['Drawdown'] = calculate_drawdown(df['Cum_Wealth'])

    return df

def calculate_drawdown(series):
    cum_max = series.cummax()
    drawdown = (series - cum_max) / cum_max
    return drawdown

def calculate_var_cvar(returns, confidence_level=0.05):
    returns = returns.dropna()
    if len(returns) == 0:
        return 0.0, 0.0
    var = np.percentile(returns, confidence_level * 100)
    cvar = returns[returns <= var].mean()
    return var, cvar

def calculate_performance(returns):
    returns = returns.dropna()
    if len(returns) == 0:
        return {"年化報酬率": 0, "年化波動率": 0, "Sharpe Ratio": 0, "最大回撤": 0, "日 VaR 5%": 0, "日 CVaR 5%": 0}

    ann_ret = (1 + returns.mean()) ** 252 - 1
    ann_vol = returns.std() * np.sqrt(252)
    sharpe = ann_ret / ann_vol if ann_vol != 0 else 0
    cum_ret = (1 + returns).cumprod()
    mdd = calculate_drawdown(cum_ret).min()
    var, cvar = calculate_var_cvar(returns)

    return {
        "年化報酬率": ann_ret,
        "年化波動率": ann_vol,
        "Sharpe Ratio": sharpe,
        "最大回撤": mdd,
        "日 VaR 5%": var,
        "日 CVaR 5%": cvar
    }

def run_backtest(df, short_window, long_window, transaction_cost):
    close = df['Close']
    short_ma = close.rolling(window=short_window).mean()
    long_ma = close.rolling(window=long_window).mean()

    position = np.where(short_ma > long_ma, 1, 0)
    position = pd.Series(position, index=df.index).shift(1).fillna(0)

    daily_ret = close.pct_change()
    trades = position.diff().abs()

    strat_ret = position * daily_ret - transaction_cost * trades

    trades_count = trades.sum()

    perf_bnh = calculate_performance(daily_ret)
    perf_strat = calculate_performance(strat_ret)
    perf_bnh["交易次數"] = 0
    perf_strat["交易次數"] = trades_count

    df_ret = pd.DataFrame({
        'BnH_Return': daily_ret,
        'Strat_Return': strat_ret,
        'BnH_Wealth': (1 + daily_ret.fillna(0)).cumprod(),
        'Strat_Wealth': (1 + strat_ret.fillna(0)).cumprod()
    })
    df_ret['Strat_Drawdown'] = calculate_drawdown(df_ret['Strat_Wealth'])

    return perf_bnh, perf_strat, df_ret

def run_stock_risk_simulation(returns, initial_capital, position_size, n_trades, n_simulations, ruin_threshold):
    returns = returns.dropna().values
    if len(returns) == 0:
        return np.zeros((n_simulations, n_trades + 1))

    sim_returns = np.random.choice(returns, size=(n_simulations, n_trades), replace=True)
    wealth_paths = np.zeros((n_simulations, n_trades + 1))
    wealth_paths[:, 0] = initial_capital

    for i in range(1, n_trades + 1):
        investment = wealth_paths[:, i-1] * position_size
        cash = wealth_paths[:, i-1] - investment
        wealth_paths[:, i] = cash + investment * (1 + sim_returns[:, i-1])
        ruined = wealth_paths[:, i] <= ruin_threshold
        wealth_paths[ruined, i:] = ruin_threshold

    return wealth_paths

def generate_technical_summary(df, ticker):
    latest = df.iloc[-1]
    return f"""
    標的: {ticker}
    最新收盤價: {latest.get('Close', 0):.2f}
    SMA20: {latest.get('SMA20', 0):.2f}
    SMA60: {latest.get('SMA60', 0):.2f}
    RSI14: {latest.get('RSI14', 0):.2f}
    MACD: {latest.get('MACD', 0):.4f}
    布林通道上緣: {latest.get('BB_upper', 0):.2f}
    布林通道下緣: {latest.get('BB_lower', 0):.2f}
    """

def generate_backtest_summary(ticker, bnh, strat, short_w, long_w):
    return f"""
    標的: {ticker}
    策略: 均線交叉 ({short_w} MA / {long_w} MA)
    Buy and Hold 年化報酬: {bnh['年化報酬率']:.2%} | 最大回撤: {bnh['最大回撤']:.2%} | Sharpe: {bnh['Sharpe Ratio']:.2f}
    Strategy 年化報酬: {strat['年化報酬率']:.2%} | 最大回撤: {strat['最大回撤']:.2%} | Sharpe: {strat['Sharpe Ratio']:.2f}
    交易次數: {strat['交易次數']}
    """

def generate_portfolio_summary(tickers, perf_df, weights_df):
    return f"""
    投資組合標的: {', '.join(tickers)}
    績效表現:
    {perf_df.to_string()}
    權重配置:
    {weights_df.to_string()}
    """

def generate_stock_risk_summary(ticker, stats):
    summary = f"標的: {ticker} 蒙地卡羅風險模擬結果:\n"
    for k, v in stats.items():
        if isinstance(v, float) and abs(v) < 100 and '%' not in k:
            summary += f"{k}: {v:.2%}\n"
        elif isinstance(v, float):
            summary += f"{k}: {v:.2f}\n"
        else:
            summary += f"{k}: {v}\n"
    return summary

def display_disclaimer():
    st.warning("⚠️ **免責聲明**：本平台分析結果僅供課程實作、研究與資訊展示參考。所有計算與 AI 解析均不構成任何買賣、投資建議或獲利保證。實際投資前請自行評估風險。")

# ==========================================
# 2. Sidebar Navigation
# ==========================================

st.sidebar.title("AI 智能投資分析平台")
page = st.sidebar.radio(
    "導覽選單",
    ["首頁", "Mission 1：AI 技術分析", "Mission 2：策略回測", "Mission 3：個股報告", "Mission 4：智能投資組合", "Mission 5：風險管理"]
)

# ==========================================
# 3. Pages Implementation
# ==========================================

if page == "首頁":
    st.title("📊 AI 智能投資分析平台")
    display_disclaimer()

    st.markdown("""
    歡迎來到 AI 智能投資分析平台。本平台整合量化計算與 Generative AI，提供以下五大任務模組：

    *   **Mission 1：AI 技術分析** - 自動計算技術指標（SMA, RSI, MACD, Bollinger Bands）並由 AI 進行客觀盤勢解讀。
    *   **Mission 2：策略回測** - 實作均線交叉策略，對比 Buy & Hold 績效，計算年化報酬、Sharpe Ratio 等關鍵指標。
    *   **Mission 3：個股報告** - 整合技術面與策略回測結果，一鍵生成結構化之 AI 個股研究報告。
    *   **Mission 4：智能投資組合** - 透過 AI Score 排序標的，建構等權重、反波動與最小變異數投資組合。
    *   **Mission 5：風險管理** - 運用蒙地卡羅模擬 (Monte Carlo Simulation) 評估資金路徑與破產機率。
    """)
    st.expander("AI 使用限制聲明").markdown("本平台呼叫 Gemini API 時已嚴格限制：不提供目標價、不提供買賣建議、不保證績效。")

elif page == "Mission 1：AI 技術分析":
    st.title("📈 Mission 1：AI 技術分析")
    display_disclaimer()

    col1, col2 = st.columns(2)
    with col1:
        ticker = st.text_input("股票代號", "2330.TW")
    with col2:
        start_date = st.date_input("開始日期", pd.to_datetime("2023-01-01"))
        end_date = st.date_input("結束日期", pd.to_datetime("today"))

    if st.button("開始技術分析"):
        try:
            with st.spinner("下載與計算中..."):
                df = download_stock_data(ticker, start_date, end_date)
                if df.empty:
                    st.error("查無資料，請確認股票代號或日期區間。")
                else:
                    df = calculate_indicators(df)
                    st.session_state['m1_df'] = df
                    st.session_state['m1_ticker'] = ticker

                    st.subheader("最新技術指標")
                    latest_df = df.tail(5).sort_index(ascending=False).round(4)
                    st.dataframe(latest_df[['Close', 'SMA20', 'SMA60', 'RSI14', 'MACD', 'BB_upper', 'BB_lower']])

                    fig, axs = plt.subplots(4, 1, figsize=(10, 15), sharex=True)

                    axs[0].plot(df.index, df['Close'], label='Close')
                    axs[0].plot(df.index, df['SMA20'], label='SMA20')
                    axs[0].plot(df.index, df['SMA60'], label='SMA60')
                    axs[0].set_title(f"{ticker} Price & SMA")
                    axs[0].legend()
                    axs[0].grid()

                    axs[1].plot(df.index, df['RSI14'], color='purple')
                    axs[1].axhline(70, color='red', linestyle='--')
                    axs[1].axhline(30, color='green', linestyle='--')
                    axs[1].set_title("RSI 14")
                    axs[1].grid()

                    axs[2].plot(df.index, df['MACD'], label='MACD')
                    axs[2].plot(df.index, df['MACD_signal'], label='Signal')
                    axs[2].bar(df.index, df['MACD_diff'], label='Diff', color='gray')
                    axs[2].set_title("MACD")
                    axs[2].legend()
                    axs[2].grid()

                    axs[3].plot(df.index, df['Close'], label='Close')
                    axs[3].plot(df.index, df['BB_upper'], label='Upper', linestyle='--')
                    axs[3].plot(df.index, df['BB_lower'], label='Lower', linestyle='--')
                    axs[3].set_title("Bollinger Bands")
                    axs[3].legend()
                    axs[3].grid()

                    st.pyplot(fig)
                    plt.close(fig)

                    fig2, ax = plt.subplots(figsize=(10, 4))
                    ax.fill_between(df.index, df['Drawdown'], 0, color='red', alpha=0.3)
                    ax.set_title("Drawdown")
                    ax.grid()
                    st.pyplot(fig2)
                    plt.close(fig2)

                    summary = generate_technical_summary(df, ticker)
                    st.session_state['m1_summary'] = summary
                    st.success("計算完成！")
        except Exception as e:
            st.error(f"執行時發生錯誤: {e}")

    if 'm1_summary' in st.session_state:
        st.subheader("技術分析摘要")
        st.text_area("Technical Summary", st.session_state['m1_summary'], height=150)

        if st.button("產生 AI 技術分析解讀"):
            with st.spinner("AI 分析中..."):
                resp = get_gemini_response(st.session_state['m1_summary'])
                if resp:
                    st.markdown(f"### 🤖 AI 解讀\n{resp}")
                else:
                    st.info("尚未設定 Gemini API Key，AI 分析暫時無法使用。")

elif page == "Mission 2：策略回測":
    st.title("🔄 Mission 2：策略回測")
    display_disclaimer()

    col1, col2, col3 = st.columns(3)
    with col1:
        ticker = st.text_input("股票代號", "2330.TW", key='m2_ticker')
        start_date = st.date_input("開始日期", pd.to_datetime("2020-01-01"), key='m2_start')
    with col2:
        short_w = st.number_input("短期均線", value=20, min_value=1)
        end_date = st.date_input("結束日期", pd.to_datetime("today"), key='m2_end')
    with col3:
        long_w = st.number_input("長期均線", value=60, min_value=2)
        cost = st.number_input("單邊交易成本", value=0.001425, format="%.6f")

    if st.button("開始回測"):
        try:
            with st.spinner("回測運算中..."):
                df = download_stock_data(ticker, start_date, end_date)
                if df.empty or len(df) < long_w:
                    st.error("資料不足以進行回測，請延長日期或更換標的。")
                else:
                    bnh, strat, df_ret = run_backtest(df, short_w, long_w, cost)

                    st.subheader("績效比較表")
                    perf_df = pd.DataFrame([bnh, strat], index=['Buy and Hold', 'Strategy']).T
                    st.dataframe(perf_df.style.format("{:.4f}"))

                    fig, ax = plt.subplots(2, 1, figsize=(10, 10), sharex=True)
                    ax[0].plot(df_ret.index, df_ret['BnH_Wealth'], label='Buy & Hold')
                    ax[0].plot(df_ret.index, df_ret['Strat_Wealth'], label='Strategy')
                    ax[0].set_title("Cumulative Wealth")
                    ax[0].legend()
                    ax[0].grid()

                    ax[1].fill_between(df_ret.index, df_ret['Strat_Drawdown'], 0, color='red', alpha=0.3)
                    ax[1].set_title("Strategy Drawdown")
                    ax[1].grid()

                    st.pyplot(fig)
                    plt.close(fig)

                    summary = generate_backtest_summary(ticker, bnh, strat, short_w, long_w)
                    st.session_state['m2_summary'] = summary
                    st.success("回測完成！")
        except Exception as e:
            st.error(f"執行時發生錯誤: {e}")

    if 'm2_summary' in st.session_state:
        st.subheader("回測摘要")
        st.text_area("Backtest Summary", st.session_state['m2_summary'], height=150)

        if st.button("產生 AI 回測解讀"):
            with st.spinner("AI 分析中..."):
                resp = get_gemini_response(st.session_state['m2_summary'])
                if resp:
                    st.markdown(f"### 🤖 AI 解讀\n{resp}")
                else:
                    st.info("尚未設定 Gemini API Key，AI 分析暫時無法使用。")

elif page == "Mission 3：個股報告":
    st.title("📄 Mission 3：個股報告")
    display_disclaimer()

    col1, col2, col3 = st.columns(3)
    with col1:
        ticker = st.text_input("股票代號", "2330.TW", key='m3_ticker')
    with col2:
        start_date = st.date_input("開始日期", pd.to_datetime("2023-01-01"), key='m3_start')
        short_w = st.number_input("短期均線", value=20, min_value=1, key='m3_short')
    with col3:
        end_date = st.date_input("結束日期", pd.to_datetime("today"), key='m3_end')
        long_w = st.number_input("長期均線", value=60, min_value=2, key='m3_long')

    if st.button("產生個股報告"):
        try:
            with st.spinner("整合數據與生成報告中..."):
                df = download_stock_data(ticker, start_date, end_date)
                if df.empty or len(df) < long_w:
                    st.error("資料不足。")
                else:
                    df_tech = calculate_indicators(df.copy())
                    tech_sum = generate_technical_summary(df_tech, ticker)

                    bnh, strat, df_ret = run_backtest(df.copy(), short_w, long_w, 0.001425)
                    backtest_sum = generate_backtest_summary(ticker, bnh, strat, short_w, long_w)

                    report_package = f"【綜合分析資料包】\n資料期間: {start_date} ~ {end_date}\n" + tech_sum + "\n" + backtest_sum
                    st.session_state['m3_report'] = report_package

                    st.subheader("原始數據封包 (Report Package)")
                    st.text_area("Data", report_package, height=200)

                    resp = get_gemini_response(report_package)
                    if resp:
                        st.markdown("### 🤖 AI 完整個股分析報告")
                        st.markdown(resp)
                    else:
                        st.info("尚未設定 Gemini API Key，AI 分析暫時無法使用。已產生基礎數據封包。")
        except Exception as e:
            st.error(f"執行時發生錯誤: {e}")

elif page == "Mission 4：智能投資組合":
    st.title("🥧 Mission 4：智能投資組合")
    display_disclaimer()

    tickers_input = st.text_input("輸入多檔股票代號 (以逗號分隔)", "2330.TW, 2317.TW, 2454.TW, 2303.TW")
    col1, col2 = st.columns(2)
    with col1:
        start_date = st.date_input("開始日期", pd.to_datetime("2020-01-01"), key='m4_start')
    with col2:
        end_date = st.date_input("結束日期", pd.to_datetime("today"), key='m4_end')

    if st.button("開始投資組合分析"):
        try:
            tickers = [t.strip() for t in tickers_input.split(",")]
            with st.spinner("下載與運算中..."):
                data = yf.download(tickers, start=start_date, end=end_date)
                if isinstance(data.columns, pd.MultiIndex):
                    prices = data['Close']
                else:
                    prices = data

                prices = prices.dropna(axis=1, how='all').ffill().dropna()
                valid_tickers = prices.columns.tolist()
                returns = prices.pct_change().dropna()

                scores = []
                for t in valid_tickers:
                    p = prices[t]
                    r = returns[t]
                    perf = calculate_performance(r)

                    # Trend calc
                    sma20 = p.rolling(20).mean().iloc[-1]
                    sma60 = p.rolling(60).mean().iloc[-1]
                    last_p = p.iloc[-1]
                    trend_score = 0
                    if last_p > sma20: trend_score += 10
                    if last_p > sma60: trend_score += 10

                    # RSI calc
                    delta = p.diff()
                    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean().iloc[-1]
                    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean().iloc[-1]
                    if loss == 0: rsi = 100
                    else: rsi = 100 - (100 / (1 + gain/loss))
                    rsi_score = 15 if 40 <= rsi <= 70 else (5 if rsi > 70 else 10)

                    scores.append({
                        "Ticker": t,
                        "Ann_Ret": perf["年化報酬率"],
                        "Ann_Vol": perf["年化波動率"],
                        "Sharpe": perf["Sharpe Ratio"],
                        "MDD": perf["最大回撤"],
                        "RSI": rsi,
                        "TrendScore": trend_score,
                        "RSIScore": rsi_score
                    })

                df_scores = pd.DataFrame(scores).set_index("Ticker")
                # Normalize Sharpe (40)
                min_s, max_s = df_scores['Sharpe'].min(), df_scores['Sharpe'].max()
                if max_s > min_s:
                    df_scores['SharpeScore'] = (df_scores['Sharpe'] - min_s) / (max_s - min_s) * 40
                else:
                    df_scores['SharpeScore'] = 20

                # Normalize MDD (25) - smaller drop is better
                min_m, max_m = df_scores['MDD'].min(), df_scores['MDD'].max()
                if max_m > min_m:
                    df_scores['MDDScore'] = (df_scores['MDD'] - min_m) / (max_m - min_m) * 25
                else:
                    df_scores['MDDScore'] = 12.5

                df_scores['AIScore'] = df_scores['SharpeScore'] + df_scores['MDDScore'] + df_scores['RSIScore'] + df_scores['TrendScore']
                df_scores = df_scores.sort_values("AIScore", ascending=False)

                # Portfolio Weights
                n = len(valid_tickers)
                eq_w = np.ones(n) / n

                inv_vol_w = 1.0 / df_scores.loc[valid_tickers, 'Ann_Vol'].values
                inv_vol_w = inv_vol_w / np.sum(inv_vol_w)

                cov_matrix = returns.cov() * 252
                def port_vol(weights):
                    return np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
                cons = ({'type': 'eq', 'fun': lambda x: np.sum(x) - 1})
                bnds = tuple((0, 1) for _ in range(n))
                min_var_res = sco.minimize(port_vol, eq_w, method='SLSQP', bounds=bnds, constraints=cons)
                min_var_w = min_var_res.x

                df_weights = pd.DataFrame({
                    "Equal": eq_w,
                    "InvVol": inv_vol_w,
                    "MinVar": min_var_w
                }, index=valid_tickers)

                # Port Returns
                port_ret = pd.DataFrame(index=returns.index)
                port_ret['Equal'] = returns.dot(eq_w)
                port_ret['InvVol'] = returns.dot(inv_vol_w)
                port_ret['MinVar'] = returns.dot(min_var_w)

                port_perf = pd.DataFrame({
                    "Equal": calculate_performance(port_ret['Equal']),
                    "InvVol": calculate_performance(port_ret['InvVol']),
                    "MinVar": calculate_performance(port_ret['MinVar'])
                }).T

                st.subheader("AI Score 排名")
                st.dataframe(df_scores[['AIScore', 'SharpeScore', 'MDDScore', 'RSIScore', 'TrendScore', 'Ann_Ret', 'MDD']].style.format("{:.4f}"))

                col_w, col_p = st.columns(2)
                with col_w:
                    st.subheader("投資組合權重")
                    st.dataframe(df_weights.style.format("{:.2%}"))
                with col_p:
                    st.subheader("投資組合績效")
                    st.dataframe(port_perf[['年化報酬率', '年化波動率', 'Sharpe Ratio', '最大回撤']].style.format("{:.4f}"))

                fig, axs = plt.subplots(1, 3, figsize=(18, 5))

                df_scores['AIScore'].plot(kind='bar', ax=axs[0], color='skyblue')
                axs[0].set_title("AI Score Ranking")
                axs[0].set_ylabel("Score")

                (1 + port_ret).cumprod().plot(ax=axs[1])
                axs[1].set_title("Portfolio Cumulative Wealth")
                axs[1].grid()

                df_weights.plot(kind='bar', ax=axs[2])
                axs[2].set_title("Weights Comparison")
                axs[2].set_ylabel("Weight")

                st.pyplot(fig)
                plt.close(fig)

                summary = generate_portfolio_summary(valid_tickers, port_perf, df_weights)
                st.session_state['m4_summary'] = summary

        except Exception as e:
            st.error(f"執行時發生錯誤: {e}")

    if 'm4_summary' in st.session_state:
        st.subheader("投資組合摘要")
        st.text_area("Portfolio Summary", st.session_state['m4_summary'], height=150)

        if st.button("產生 AI 投資組合解讀"):
            with st.spinner("AI 分析中..."):
                resp = get_gemini_response(st.session_state['m4_summary'])
                if resp:
                    st.markdown(f"### 🤖 AI 解讀\n{resp}")
                else:
                    st.info("尚未設定 Gemini API Key，AI 分析暫時無法使用。")

elif page == "Mission 5：風險管理":
    st.title("🛡️ Mission 5：風險管理 (蒙地卡羅模擬)")
    display_disclaimer()

    col1, col2, col3 = st.columns(3)
    with col1:
        ticker = st.text_input("股票代號", "2330.TW", key='m5_ticker')
        start_date = st.date_input("歷史資料起點", pd.to_datetime("2020-01-01"), key='m5_start')
        end_date = st.date_input("歷史資料終點", pd.to_datetime("today"), key='m5_end')
    with col2:
        init_cap = st.number_input("初始資金", value=100000)
        pos_size = st.number_input("每次投入比例 (0-1)", value=1.0, min_value=0.1, max_value=1.0)
        ruin_th = st.number_input("破產門檻", value=50000)
    with col3:
        n_trades = st.number_input("每條路徑交易次數(天)", value=252)
        n_sims = st.number_input("模擬路徑數", value=1000)

    if st.button("開始股票風險模擬"):
        try:
            with st.spinner("蒙地卡羅模擬中..."):
                df = download_stock_data(ticker, start_date, end_date)
                if df.empty:
                    st.error("查無歷史資料。")
                else:
                    returns = df['Close'].pct_change().dropna()
                    paths = run_stock_risk_simulation(returns, init_cap, pos_size, n_trades, n_sims, ruin_th)

                    final_wealth = paths[:, -1]
                    max_drawdowns = []
                    for i in range(n_sims):
                        series = pd.Series(paths[i])
                        md = calculate_drawdown(series).min()
                        max_drawdowns.append(md)
                    max_drawdowns = np.array(max_drawdowns)

                    hist_var, hist_cvar = calculate_var_cvar(returns)

                    stats = {
                        "平均日報酬率": returns.mean(),
                        "日報酬率標準差": returns.std(),
                        "歷史最大單日漲幅": returns.max(),
                        "歷史最大單日跌幅": returns.min(),
                        "平均期末財富": np.mean(final_wealth),
                        "期末財富中位數": np.median(final_wealth),
                        "最低期末財富": np.min(final_wealth),
                        "最高期末財富": np.max(final_wealth),
                        "歷史日 VaR 5%": hist_var,
                        "歷史日 CVaR 5%": hist_cvar,
                        "模擬平均最大回撤": np.mean(max_drawdowns),
                        "模擬最差最大回撤": np.min(max_drawdowns),
                        "破產機率 (低於門檻)": np.sum(final_wealth <= ruin_th) / n_sims
                    }

                    st.subheader("風險統計表")
                    st.dataframe(pd.Series(stats, name="數值").to_frame().style.format("{:.4f}"))

                    fig, axs = plt.subplots(1, 3, figsize=(18, 5))

                    for i in range(min(50, n_sims)):
                        axs[0].plot(paths[i], alpha=0.5)
                    axs[0].axhline(ruin_th, color='red', linestyle='--', label='Ruin Threshold')
                    axs[0].set_title(f"First 50 Simulated Paths ({n_trades} trades)")
                    axs[0].set_xlabel("Trades")
                    axs[0].set_ylabel("Wealth")
                    axs[0].legend()
                    axs[0].grid()

                    axs[1].hist(final_wealth, bins=50, color='skyblue', edgecolor='black')
                    axs[1].axvline(init_cap, color='red', linestyle='--', label='Initial Capital')
                    axs[1].set_title("Final Wealth Distribution")
                    axs[1].set_xlabel("Final Wealth")
                    axs[1].legend()
                    axs[1].grid()

                    axs[2].hist(max_drawdowns, bins=50, color='salmon', edgecolor='black')
                    axs[2].set_title("Max Drawdown Distribution")
                    axs[2].set_xlabel("Max Drawdown")
                    axs[2].grid()

                    st.pyplot(fig)
                    plt.close(fig)

                    summary = generate_stock_risk_summary(ticker, stats)
                    st.session_state['m5_summary'] = summary
        except Exception as e:
            st.error(f"執行時發生錯誤: {e}")

    if 'm5_summary' in st.session_state:
        st.subheader("風險模擬摘要")
        st.text_area("Risk Summary", st.session_state['m5_summary'], height=200)

        if st.button("產生 AI 股票風險解讀"):
            with st.spinner("AI 分析中..."):
                resp = get_gemini_response(st.session_state['m5_summary'])
                if resp:
                    st.markdown(f"### 🤖 AI 解讀\n{resp}")
                else:
                    st.info("尚未設定 Gemini API Key，AI 分析暫時無法使用。")